import { createAsyncThunk, createSlice, isAnyOf } from "@reduxjs/toolkit";
import { FieldValues } from "react-hook-form";
import { toast } from "react-toastify";
import { history } from "../..";
import agent from "../../app/api/agent";
import { User } from "../../app/models/user";
import { setBasket } from "../basket/basketSlice";

interface AccountState { // set account state = user : user or null
    user: User | null;
}

const initialState: AccountState = { // set initial account state to null user
    user: null
}

// thunk is the standard way to define async action creators in redux
// createAsyncThunk receives action type (signIn) and callback function (below login try/catch logic) and returns async promise
export const signInUser = createAsyncThunk<User, FieldValues>(
    'account/signInUser', // name this action type

    // generate promise lifecycle action type named above
    // thunkAPI is an object containing all of the parameters that are normally passed to a Redux thunk function, 
    // as well as additional options::: dispatch, getState, requestId (autoGenerated, unique to each http request)    || CONT. BELOW |/ 
    //       : signal; an object that may be used to see if another part of the app logic has marked this request as needing cancelation  ||CONT. BELOW |/ 
    //       : payload; an object that contains the 'data', used in below function, as we call it directly   ::: 
    async (data, thunkAPI) => { // also,'data' payload taken from our request (username, password, ssl token)
        try {
            const userDto = await agent.Account.login(data); // try async login with our parameters
            const { basket, ...user } = userDto; // 
            // returns thunk action creator that runs the promise callback 
            if (basket) thunkAPI.dispatch(setBasket(basket));
            localStorage.setItem('user', JSON.stringify(user));
            return user;
        } catch (error: any) {
            return thunkAPI.rejectWithValue({error: error.data});
        }
    }
)

export const fetchCurrentUser = createAsyncThunk<User>(
    'account/fetchCurrentUser',
    async (_, thunkAPI) => {
        thunkAPI.dispatch(setUser(JSON.parse(localStorage.getItem('user')!)));
        try {
            const userDto = await agent.Account.currentUser();
            const {basket, ...user} = userDto;
            if (basket) thunkAPI.dispatch(setBasket(basket));
            localStorage.setItem('user', JSON.stringify(user));
            return user;
        } catch (error: any) {
            return thunkAPI.rejectWithValue({error: error.data});
        }
    },
    {
        condition: () => {
            if (!localStorage.getItem('user')) return false;
        }
    }
)

// signOut reducer takes state and logs user out, removes userInfo from localstorage, pushes history to root url
// setUser reducer takes state + action and decodes our json web token into string, evaluates that string against msft dbset
// to get associated roles, and then sets new user state = copy of prior action payload (signin) where
export const accountSlice = createSlice({
    name: 'account',
    initialState,
    reducers: {
        signOut: (state) => {
            state.user = null;
            localStorage.removeItem('user');
            history.push('/');
        },
        setUser: (state, action) => {
            let claims = JSON.parse(atob(action.payload.token.split('.')[1]));
            let roles = claims['http://schemas.microsoft.com/ws/2008/06/identity/claims/role'];
            state.user = {...action.payload, roles: typeof(roles) === 'string' ? [roles] : roles};
        }
    },
    extraReducers: (builder => {
        builder.addCase(fetchCurrentUser.rejected, (state) => {
            state.user = null;
            localStorage.removeItem('user');
            toast.error('Session expired - please login again');
            history.push('/');
        });
        builder.addMatcher(isAnyOf(signInUser.fulfilled, fetchCurrentUser.fulfilled), (state, action) => {
            let claims = JSON.parse(atob(action.payload.token.split('.')[1]));
            let roles = claims['http://schemas.microsoft.com/ws/2008/06/identity/claims/role'];
            state.user = {...action.payload, roles: typeof(roles) === 'string' ? [roles] : roles};
        });
        builder.addMatcher(isAnyOf(signInUser.rejected), (state, action) => {
            throw action.payload;
        })
    })
})

export const {signOut, setUser} = accountSlice.actions;